title: Andy's space
description:Where of what's past is prologue.
author: Xiangyu Li
avatar: /logo.png
email: duanglxy163@163.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
#twitter:
#  username: ngzhio
#  card: summary
logo: logo.png
social:
  name: Xiangyu Li
  links:
#    - https://twitter.com/ngzhio
#    - https://www.facebook.com/ngzhio
    - https://github.com/andyspace
#google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
